package com.payment.mapper.bnbordermapper;
import com.payment.entity.bnborder.OrderTaskEntity;

import java.util.List;
import java.util.Map;

public interface OrderTaskDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int insert(OrderTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int insertSelective(OrderTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    OrderTaskEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTaskEntity record);

    List<OrderTaskEntity> selectList(Map<String, Object> params);

   int updateCompensateTask(Map<String, Object> map);
}