package com.payment.entity.bnborder;

import java.util.Date;
import java.util.List;

public class OrderTaskEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.orderId
     *
     * @mbggenerated
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.busiTransNo
     *
     * @mbggenerated
     */
    private String busiTransNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.statusId
     *
     * @mbggenerated
     */
    private Short statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.jobId
     *
     * @mbggenerated
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.jobType
     *
     * @mbggenerated
     */
    private Short jobType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.retries
     *
     * @mbggenerated
     */
    private Short retries;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.createdTime
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_task.dataChange_lastTime
     *
     * @mbggenerated
     */
    private Date dataChange_lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.id
     *
     * @return the value of order_task.id
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.id
     *
     * @param id the value for order_task.id
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.orderId
     *
     * @return the value of order_task.orderId
     * @mbggenerated
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.orderId
     *
     * @param orderId the value for order_task.orderId
     * @mbggenerated
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.busiTransNo
     *
     * @return the value of order_task.busiTransNo
     * @mbggenerated
     */
    public String getBusiTransNo() {
        return busiTransNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.busiTransNo
     *
     * @param busiTransNo the value for order_task.busiTransNo
     * @mbggenerated
     */
    public void setBusiTransNo(String busiTransNo) {
        this.busiTransNo = busiTransNo == null ? null : busiTransNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.statusId
     *
     * @return the value of order_task.statusId
     * @mbggenerated
     */
    public Short getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.statusId
     *
     * @param statusId the value for order_task.statusId
     * @mbggenerated
     */
    public void setStatusId(Short statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.jobId
     *
     * @return the value of order_task.jobId
     * @mbggenerated
     */
    public String getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.jobId
     *
     * @param jobId the value for order_task.jobId
     * @mbggenerated
     */
    public void setJobId(String jobId) {
        this.jobId = jobId == null ? null : jobId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.jobType
     *
     * @return the value of order_task.jobType
     * @mbggenerated
     */
    public Short getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.jobType
     *
     * @param jobType the value for order_task.jobType
     * @mbggenerated
     */
    public void setJobType(Short jobType) {
        this.jobType = jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.retries
     *
     * @return the value of order_task.retries
     * @mbggenerated
     */
    public Short getRetries() {
        return retries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.retries
     *
     * @param retries the value for order_task.retries
     * @mbggenerated
     */
    public void setRetries(Short retries) {
        this.retries = retries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.createdTime
     *
     * @return the value of order_task.createdTime
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.createdTime
     *
     * @param createdTime the value for order_task.createdTime
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_task.dataChange_lastTime
     *
     * @return the value of order_task.dataChange_lastTime
     * @mbggenerated
     */
    public Date getDataChange_lastTime() {
        return dataChange_lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_task.dataChange_lastTime
     *
     * @param dataChange_lastTime the value for order_task.dataChange_lastTime
     * @mbggenerated
     */
    public void setDataChange_lastTime(Date dataChange_lastTime) {
        this.dataChange_lastTime = dataChange_lastTime;
    }


    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    private Integer limit;


    public List<Integer> getListJobType() {
        return listJobType;
    }

    public void setListJobType(List<Integer> listJobType) {
        this.listJobType = listJobType;
    }

    private List<Integer> listJobType;


    public enum JobTypeEnum {
        Submit(11, "提交订单"),
        Pay(12, "支付"),
        Query(13, "同步订单");

        JobTypeEnum(int code, String desc) {
            this.code = code;
            this.desc = desc;
        }

        private int code;
        private String desc;

        public int getCode() {
            return code;
        }

        public void setCode(int code) {
            this.code = code;
        }

        public String getDesc() {
            return desc;
        }

        public void setDesc(String desc) {
            this.desc = desc;
        }


        public static JobTypeEnum getItemByName(String name) {
            for (JobTypeEnum item : JobTypeEnum.values()) {
                if (item.name().equals(name)) {
                    return item;
                }
            }
            return null;
        }


        public static JobTypeEnum getItemByCode(int typeCode) {
            for (JobTypeEnum statusEnum : JobTypeEnum.values()) {
                if (statusEnum.getCode() == typeCode) {
                    return statusEnum;
                }
            }
            return null;
        }
    }

}