package com.payment.service.bnborderservice;

import com.payment.entity.bnborder.OrderTaskEntity;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Created by shi_y on 2016/9/8.
 */
@Repository
public interface OrderTaskService {

    List<OrderTaskEntity> selectList(String jobId, Integer statusId, List<Integer> jobType, Integer retries);

    int updateByPrimaryKeySelective(OrderTaskEntity entity);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int insert(OrderTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int insertSelective(OrderTaskEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    OrderTaskEntity selectByPrimaryKey(Long id);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderTaskEntity record);


    /**
     *
     * @param time
     * @return
     */
    int updateCompensateTask(String time);

}


