package com.payment.entity.groupwormhole;

import java.math.BigDecimal;
import java.util.Date;

public class BnbHotelEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.hotelId
     *
     * @mbggenerated
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.hotelName
     *
     * @mbggenerated
     */
    private String hotelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.sourceId
     *
     * @mbggenerated
     */
    private Integer sourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.sourceHotelId
     *
     * @mbggenerated
     */
    private String sourceHotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.cityId
     *
     * @mbggenerated
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.lng
     *
     * @mbggenerated
     */
    private BigDecimal lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.lat
     *
     * @mbggenerated
     */
    private BigDecimal lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.coordinateType
     *
     * @mbggenerated
     */
    private Byte coordinateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_hotel.dataChange_lastTime
     *
     * @mbggenerated
     */
    private Date dataChange_lastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.hotelId
     *
     * @return the value of bnb_hotel.hotelId
     *
     * @mbggenerated
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.hotelId
     *
     * @param hotelId the value for bnb_hotel.hotelId
     *
     * @mbggenerated
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.hotelName
     *
     * @return the value of bnb_hotel.hotelName
     *
     * @mbggenerated
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.hotelName
     *
     * @param hotelName the value for bnb_hotel.hotelName
     *
     * @mbggenerated
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.sourceId
     *
     * @return the value of bnb_hotel.sourceId
     *
     * @mbggenerated
     */
    public Integer getSourceId() {
        return sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.sourceId
     *
     * @param sourceId the value for bnb_hotel.sourceId
     *
     * @mbggenerated
     */
    public void setSourceId(Integer sourceId) {
        this.sourceId = sourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.sourceHotelId
     *
     * @return the value of bnb_hotel.sourceHotelId
     *
     * @mbggenerated
     */
    public String getSourceHotelId() {
        return sourceHotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.sourceHotelId
     *
     * @param sourceHotelId the value for bnb_hotel.sourceHotelId
     *
     * @mbggenerated
     */
    public void setSourceHotelId(String sourceHotelId) {
        this.sourceHotelId = sourceHotelId == null ? null : sourceHotelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.cityId
     *
     * @return the value of bnb_hotel.cityId
     *
     * @mbggenerated
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.cityId
     *
     * @param cityId the value for bnb_hotel.cityId
     *
     * @mbggenerated
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.address
     *
     * @return the value of bnb_hotel.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.address
     *
     * @param address the value for bnb_hotel.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.lng
     *
     * @return the value of bnb_hotel.lng
     *
     * @mbggenerated
     */
    public BigDecimal getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.lng
     *
     * @param lng the value for bnb_hotel.lng
     *
     * @mbggenerated
     */
    public void setLng(BigDecimal lng) {
        this.lng = lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.lat
     *
     * @return the value of bnb_hotel.lat
     *
     * @mbggenerated
     */
    public BigDecimal getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.lat
     *
     * @param lat the value for bnb_hotel.lat
     *
     * @mbggenerated
     */
    public void setLat(BigDecimal lat) {
        this.lat = lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.coordinateType
     *
     * @return the value of bnb_hotel.coordinateType
     *
     * @mbggenerated
     */
    public Byte getCoordinateType() {
        return coordinateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.coordinateType
     *
     * @param coordinateType the value for bnb_hotel.coordinateType
     *
     * @mbggenerated
     */
    public void setCoordinateType(Byte coordinateType) {
        this.coordinateType = coordinateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.tel
     *
     * @return the value of bnb_hotel.tel
     *
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.tel
     *
     * @param tel the value for bnb_hotel.tel
     *
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.createTime
     *
     * @return the value of bnb_hotel.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.createTime
     *
     * @param createTime the value for bnb_hotel.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_hotel.dataChange_lastTime
     *
     * @return the value of bnb_hotel.dataChange_lastTime
     *
     * @mbggenerated
     */
    public Date getDataChange_lastTime() {
        return dataChange_lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_hotel.dataChange_lastTime
     *
     * @param dataChange_lastTime the value for bnb_hotel.dataChange_lastTime
     *
     * @mbggenerated
     */
    public void setDataChange_lastTime(Date dataChange_lastTime) {
        this.dataChange_lastTime = dataChange_lastTime;
    }
}