package com.payment.entity.groupwormhole;

import java.math.BigDecimal;
import java.util.Date;

public class bnbOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.orderId
     *
     * @mbggenerated
     */
    private Long orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.orderSource
     *
     * @mbggenerated
     */
    private Integer ordersource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.vendorId
     *
     * @mbggenerated
     */
    private Integer vendorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.vendorUid
     *
     * @mbggenerated
     */
    private Long vendoruid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.vendorOrderId
     *
     * @mbggenerated
     */
    private String vendororderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.ctripOrderId
     *
     * @mbggenerated
     */
    private Long ctriporderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.productId
     *
     * @mbggenerated
     */
    private Long productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.saleAmount
     *
     * @mbggenerated
     */
    private BigDecimal saleamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.paymentAmount
     *
     * @mbggenerated
     */
    private BigDecimal paymentamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.purchaseAmount
     *
     * @mbggenerated
     */
    private BigDecimal purchaseamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.serviceFee
     *
     * @mbggenerated
     */
    private BigDecimal servicefee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.cleaningFee
     *
     * @mbggenerated
     */
    private BigDecimal cleaningfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.securityDeposit
     *
     * @mbggenerated
     */
    private BigDecimal securitydeposit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.checkIn
     *
     * @mbggenerated
     */
    private Date checkin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.checkOut
     *
     * @mbggenerated
     */
    private Date checkout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.contactName
     *
     * @mbggenerated
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.contactMobile
     *
     * @mbggenerated
     */
    private String contactmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.contactWechat
     *
     * @mbggenerated
     */
    private String contactwechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.guests
     *
     * @mbggenerated
     */
    private String guests;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.confirmationCode
     *
     * @mbggenerated
     */
    private String confirmationcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.statusId
     *
     * @mbggenerated
     */
    private Short statusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.paymentStatusId
     *
     * @mbggenerated
     */
    private Short paymentstatusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.deleteStatusId
     *
     * @mbggenerated
     */
    private Short deletestatusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.processStatusId
     *
     * @mbggenerated
     */
    private Short processstatusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.settleStatusId
     *
     * @mbggenerated
     */
    private Short settlestatusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.settleRemark
     *
     * @mbggenerated
     */
    private String settleremark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.dataChange_lastTime
     *
     * @mbggenerated
     */
    private Date datachangeLasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.hotelId
     *
     * @mbggenerated
     */
    private Long hotelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.terminalType
     *
     * @mbggenerated
     */
    private Short terminaltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.extendStatusId
     *
     * @mbggenerated
     */
    private Short extendstatusid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.orderType
     *
     * @mbggenerated
     */
    private Short ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.securityDepositType
     *
     * @mbggenerated
     */
    private Integer securitydeposittype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.ownerId
     *
     * @mbggenerated
     */
    private String ownerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.discountAmount
     *
     * @mbggenerated
     */
    private BigDecimal discountamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.totalAmount
     *
     * @mbggenerated
     */
    private BigDecimal totalamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.onlinePayRate
     *
     * @mbggenerated
     */
    private Double onlinepayrate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.onlineAmount
     *
     * @mbggenerated
     */
    private BigDecimal onlineamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.offlineAmount
     *
     * @mbggenerated
     */
    private BigDecimal offlineamount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.isBnbOrder
     *
     * @mbggenerated
     */
    private Byte isbnborder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.confirmType
     *
     * @mbggenerated
     */
    private Short confirmtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.confirmedTime
     *
     * @mbggenerated
     */
    private Date confirmedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.arriveAt
     *
     * @mbggenerated
     */
    private Integer arriveat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.cancellationPolicyType
     *
     * @mbggenerated
     */
    private Short cancellationpolicytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.cancellationPolicy
     *
     * @mbggenerated
     */
    private String cancellationpolicy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.fullRefundAheadDays
     *
     * @mbggenerated
     */
    private Integer fullrefundaheaddays;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.guestNumber
     *
     * @mbggenerated
     */
    private Integer guestnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_order.tradingRules
     *
     * @mbggenerated
     */
    private String tradingrules;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.orderId
     *
     * @return the value of bnb_order.orderId
     *
     * @mbggenerated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.orderId
     *
     * @param orderid the value for bnb_order.orderId
     *
     * @mbggenerated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.uid
     *
     * @return the value of bnb_order.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.uid
     *
     * @param uid the value for bnb_order.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.orderSource
     *
     * @return the value of bnb_order.orderSource
     *
     * @mbggenerated
     */
    public Integer getOrdersource() {
        return ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.orderSource
     *
     * @param ordersource the value for bnb_order.orderSource
     *
     * @mbggenerated
     */
    public void setOrdersource(Integer ordersource) {
        this.ordersource = ordersource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.vendorId
     *
     * @return the value of bnb_order.vendorId
     *
     * @mbggenerated
     */
    public Integer getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.vendorId
     *
     * @param vendorid the value for bnb_order.vendorId
     *
     * @mbggenerated
     */
    public void setVendorid(Integer vendorid) {
        this.vendorid = vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.vendorUid
     *
     * @return the value of bnb_order.vendorUid
     *
     * @mbggenerated
     */
    public Long getVendoruid() {
        return vendoruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.vendorUid
     *
     * @param vendoruid the value for bnb_order.vendorUid
     *
     * @mbggenerated
     */
    public void setVendoruid(Long vendoruid) {
        this.vendoruid = vendoruid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.vendorOrderId
     *
     * @return the value of bnb_order.vendorOrderId
     *
     * @mbggenerated
     */
    public String getVendororderid() {
        return vendororderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.vendorOrderId
     *
     * @param vendororderid the value for bnb_order.vendorOrderId
     *
     * @mbggenerated
     */
    public void setVendororderid(String vendororderid) {
        this.vendororderid = vendororderid == null ? null : vendororderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.ctripOrderId
     *
     * @return the value of bnb_order.ctripOrderId
     *
     * @mbggenerated
     */
    public Long getCtriporderid() {
        return ctriporderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.ctripOrderId
     *
     * @param ctriporderid the value for bnb_order.ctripOrderId
     *
     * @mbggenerated
     */
    public void setCtriporderid(Long ctriporderid) {
        this.ctriporderid = ctriporderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.productId
     *
     * @return the value of bnb_order.productId
     *
     * @mbggenerated
     */
    public Long getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.productId
     *
     * @param productid the value for bnb_order.productId
     *
     * @mbggenerated
     */
    public void setProductid(Long productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.quantity
     *
     * @return the value of bnb_order.quantity
     *
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.quantity
     *
     * @param quantity the value for bnb_order.quantity
     *
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.saleAmount
     *
     * @return the value of bnb_order.saleAmount
     *
     * @mbggenerated
     */
    public BigDecimal getSaleamount() {
        return saleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.saleAmount
     *
     * @param saleamount the value for bnb_order.saleAmount
     *
     * @mbggenerated
     */
    public void setSaleamount(BigDecimal saleamount) {
        this.saleamount = saleamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.paymentAmount
     *
     * @return the value of bnb_order.paymentAmount
     *
     * @mbggenerated
     */
    public BigDecimal getPaymentamount() {
        return paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.paymentAmount
     *
     * @param paymentamount the value for bnb_order.paymentAmount
     *
     * @mbggenerated
     */
    public void setPaymentamount(BigDecimal paymentamount) {
        this.paymentamount = paymentamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.purchaseAmount
     *
     * @return the value of bnb_order.purchaseAmount
     *
     * @mbggenerated
     */
    public BigDecimal getPurchaseamount() {
        return purchaseamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.purchaseAmount
     *
     * @param purchaseamount the value for bnb_order.purchaseAmount
     *
     * @mbggenerated
     */
    public void setPurchaseamount(BigDecimal purchaseamount) {
        this.purchaseamount = purchaseamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.serviceFee
     *
     * @return the value of bnb_order.serviceFee
     *
     * @mbggenerated
     */
    public BigDecimal getServicefee() {
        return servicefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.serviceFee
     *
     * @param servicefee the value for bnb_order.serviceFee
     *
     * @mbggenerated
     */
    public void setServicefee(BigDecimal servicefee) {
        this.servicefee = servicefee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.cleaningFee
     *
     * @return the value of bnb_order.cleaningFee
     *
     * @mbggenerated
     */
    public BigDecimal getCleaningfee() {
        return cleaningfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.cleaningFee
     *
     * @param cleaningfee the value for bnb_order.cleaningFee
     *
     * @mbggenerated
     */
    public void setCleaningfee(BigDecimal cleaningfee) {
        this.cleaningfee = cleaningfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.securityDeposit
     *
     * @return the value of bnb_order.securityDeposit
     *
     * @mbggenerated
     */
    public BigDecimal getSecuritydeposit() {
        return securitydeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.securityDeposit
     *
     * @param securitydeposit the value for bnb_order.securityDeposit
     *
     * @mbggenerated
     */
    public void setSecuritydeposit(BigDecimal securitydeposit) {
        this.securitydeposit = securitydeposit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.checkIn
     *
     * @return the value of bnb_order.checkIn
     *
     * @mbggenerated
     */
    public Date getCheckin() {
        return checkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.checkIn
     *
     * @param checkin the value for bnb_order.checkIn
     *
     * @mbggenerated
     */
    public void setCheckin(Date checkin) {
        this.checkin = checkin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.checkOut
     *
     * @return the value of bnb_order.checkOut
     *
     * @mbggenerated
     */
    public Date getCheckout() {
        return checkout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.checkOut
     *
     * @param checkout the value for bnb_order.checkOut
     *
     * @mbggenerated
     */
    public void setCheckout(Date checkout) {
        this.checkout = checkout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.contactName
     *
     * @return the value of bnb_order.contactName
     *
     * @mbggenerated
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.contactName
     *
     * @param contactname the value for bnb_order.contactName
     *
     * @mbggenerated
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.contactMobile
     *
     * @return the value of bnb_order.contactMobile
     *
     * @mbggenerated
     */
    public String getContactmobile() {
        return contactmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.contactMobile
     *
     * @param contactmobile the value for bnb_order.contactMobile
     *
     * @mbggenerated
     */
    public void setContactmobile(String contactmobile) {
        this.contactmobile = contactmobile == null ? null : contactmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.contactWechat
     *
     * @return the value of bnb_order.contactWechat
     *
     * @mbggenerated
     */
    public String getContactwechat() {
        return contactwechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.contactWechat
     *
     * @param contactwechat the value for bnb_order.contactWechat
     *
     * @mbggenerated
     */
    public void setContactwechat(String contactwechat) {
        this.contactwechat = contactwechat == null ? null : contactwechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.guests
     *
     * @return the value of bnb_order.guests
     *
     * @mbggenerated
     */
    public String getGuests() {
        return guests;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.guests
     *
     * @param guests the value for bnb_order.guests
     *
     * @mbggenerated
     */
    public void setGuests(String guests) {
        this.guests = guests == null ? null : guests.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.confirmationCode
     *
     * @return the value of bnb_order.confirmationCode
     *
     * @mbggenerated
     */
    public String getConfirmationcode() {
        return confirmationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.confirmationCode
     *
     * @param confirmationcode the value for bnb_order.confirmationCode
     *
     * @mbggenerated
     */
    public void setConfirmationcode(String confirmationcode) {
        this.confirmationcode = confirmationcode == null ? null : confirmationcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.statusId
     *
     * @return the value of bnb_order.statusId
     *
     * @mbggenerated
     */
    public Short getStatusid() {
        return statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.statusId
     *
     * @param statusid the value for bnb_order.statusId
     *
     * @mbggenerated
     */
    public void setStatusid(Short statusid) {
        this.statusid = statusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.paymentStatusId
     *
     * @return the value of bnb_order.paymentStatusId
     *
     * @mbggenerated
     */
    public Short getPaymentstatusid() {
        return paymentstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.paymentStatusId
     *
     * @param paymentstatusid the value for bnb_order.paymentStatusId
     *
     * @mbggenerated
     */
    public void setPaymentstatusid(Short paymentstatusid) {
        this.paymentstatusid = paymentstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.deleteStatusId
     *
     * @return the value of bnb_order.deleteStatusId
     *
     * @mbggenerated
     */
    public Short getDeletestatusid() {
        return deletestatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.deleteStatusId
     *
     * @param deletestatusid the value for bnb_order.deleteStatusId
     *
     * @mbggenerated
     */
    public void setDeletestatusid(Short deletestatusid) {
        this.deletestatusid = deletestatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.processStatusId
     *
     * @return the value of bnb_order.processStatusId
     *
     * @mbggenerated
     */
    public Short getProcessstatusid() {
        return processstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.processStatusId
     *
     * @param processstatusid the value for bnb_order.processStatusId
     *
     * @mbggenerated
     */
    public void setProcessstatusid(Short processstatusid) {
        this.processstatusid = processstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.settleStatusId
     *
     * @return the value of bnb_order.settleStatusId
     *
     * @mbggenerated
     */
    public Short getSettlestatusid() {
        return settlestatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.settleStatusId
     *
     * @param settlestatusid the value for bnb_order.settleStatusId
     *
     * @mbggenerated
     */
    public void setSettlestatusid(Short settlestatusid) {
        this.settlestatusid = settlestatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.settleRemark
     *
     * @return the value of bnb_order.settleRemark
     *
     * @mbggenerated
     */
    public String getSettleremark() {
        return settleremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.settleRemark
     *
     * @param settleremark the value for bnb_order.settleRemark
     *
     * @mbggenerated
     */
    public void setSettleremark(String settleremark) {
        this.settleremark = settleremark == null ? null : settleremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.createTime
     *
     * @return the value of bnb_order.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.createTime
     *
     * @param createtime the value for bnb_order.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.dataChange_lastTime
     *
     * @return the value of bnb_order.dataChange_lastTime
     *
     * @mbggenerated
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.dataChange_lastTime
     *
     * @param datachangeLasttime the value for bnb_order.dataChange_lastTime
     *
     * @mbggenerated
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.hotelId
     *
     * @return the value of bnb_order.hotelId
     *
     * @mbggenerated
     */
    public Long getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.hotelId
     *
     * @param hotelid the value for bnb_order.hotelId
     *
     * @mbggenerated
     */
    public void setHotelid(Long hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.terminalType
     *
     * @return the value of bnb_order.terminalType
     *
     * @mbggenerated
     */
    public Short getTerminaltype() {
        return terminaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.terminalType
     *
     * @param terminaltype the value for bnb_order.terminalType
     *
     * @mbggenerated
     */
    public void setTerminaltype(Short terminaltype) {
        this.terminaltype = terminaltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.extendStatusId
     *
     * @return the value of bnb_order.extendStatusId
     *
     * @mbggenerated
     */
    public Short getExtendstatusid() {
        return extendstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.extendStatusId
     *
     * @param extendstatusid the value for bnb_order.extendStatusId
     *
     * @mbggenerated
     */
    public void setExtendstatusid(Short extendstatusid) {
        this.extendstatusid = extendstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.orderType
     *
     * @return the value of bnb_order.orderType
     *
     * @mbggenerated
     */
    public Short getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.orderType
     *
     * @param ordertype the value for bnb_order.orderType
     *
     * @mbggenerated
     */
    public void setOrdertype(Short ordertype) {
        this.ordertype = ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.securityDepositType
     *
     * @return the value of bnb_order.securityDepositType
     *
     * @mbggenerated
     */
    public Integer getSecuritydeposittype() {
        return securitydeposittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.securityDepositType
     *
     * @param securitydeposittype the value for bnb_order.securityDepositType
     *
     * @mbggenerated
     */
    public void setSecuritydeposittype(Integer securitydeposittype) {
        this.securitydeposittype = securitydeposittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.ownerId
     *
     * @return the value of bnb_order.ownerId
     *
     * @mbggenerated
     */
    public String getOwnerid() {
        return ownerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.ownerId
     *
     * @param ownerid the value for bnb_order.ownerId
     *
     * @mbggenerated
     */
    public void setOwnerid(String ownerid) {
        this.ownerid = ownerid == null ? null : ownerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.remark
     *
     * @return the value of bnb_order.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.remark
     *
     * @param remark the value for bnb_order.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.discountAmount
     *
     * @return the value of bnb_order.discountAmount
     *
     * @mbggenerated
     */
    public BigDecimal getDiscountamount() {
        return discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.discountAmount
     *
     * @param discountamount the value for bnb_order.discountAmount
     *
     * @mbggenerated
     */
    public void setDiscountamount(BigDecimal discountamount) {
        this.discountamount = discountamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.totalAmount
     *
     * @return the value of bnb_order.totalAmount
     *
     * @mbggenerated
     */
    public BigDecimal getTotalamount() {
        return totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.totalAmount
     *
     * @param totalamount the value for bnb_order.totalAmount
     *
     * @mbggenerated
     */
    public void setTotalamount(BigDecimal totalamount) {
        this.totalamount = totalamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.onlinePayRate
     *
     * @return the value of bnb_order.onlinePayRate
     *
     * @mbggenerated
     */
    public Double getOnlinepayrate() {
        return onlinepayrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.onlinePayRate
     *
     * @param onlinepayrate the value for bnb_order.onlinePayRate
     *
     * @mbggenerated
     */
    public void setOnlinepayrate(Double onlinepayrate) {
        this.onlinepayrate = onlinepayrate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.onlineAmount
     *
     * @return the value of bnb_order.onlineAmount
     *
     * @mbggenerated
     */
    public BigDecimal getOnlineamount() {
        return onlineamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.onlineAmount
     *
     * @param onlineamount the value for bnb_order.onlineAmount
     *
     * @mbggenerated
     */
    public void setOnlineamount(BigDecimal onlineamount) {
        this.onlineamount = onlineamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.offlineAmount
     *
     * @return the value of bnb_order.offlineAmount
     *
     * @mbggenerated
     */
    public BigDecimal getOfflineamount() {
        return offlineamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.offlineAmount
     *
     * @param offlineamount the value for bnb_order.offlineAmount
     *
     * @mbggenerated
     */
    public void setOfflineamount(BigDecimal offlineamount) {
        this.offlineamount = offlineamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.isBnbOrder
     *
     * @return the value of bnb_order.isBnbOrder
     *
     * @mbggenerated
     */
    public Byte getIsbnborder() {
        return isbnborder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.isBnbOrder
     *
     * @param isbnborder the value for bnb_order.isBnbOrder
     *
     * @mbggenerated
     */
    public void setIsbnborder(Byte isbnborder) {
        this.isbnborder = isbnborder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.confirmType
     *
     * @return the value of bnb_order.confirmType
     *
     * @mbggenerated
     */
    public Short getConfirmtype() {
        return confirmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.confirmType
     *
     * @param confirmtype the value for bnb_order.confirmType
     *
     * @mbggenerated
     */
    public void setConfirmtype(Short confirmtype) {
        this.confirmtype = confirmtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.confirmedTime
     *
     * @return the value of bnb_order.confirmedTime
     *
     * @mbggenerated
     */
    public Date getConfirmedtime() {
        return confirmedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.confirmedTime
     *
     * @param confirmedtime the value for bnb_order.confirmedTime
     *
     * @mbggenerated
     */
    public void setConfirmedtime(Date confirmedtime) {
        this.confirmedtime = confirmedtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.arriveAt
     *
     * @return the value of bnb_order.arriveAt
     *
     * @mbggenerated
     */
    public Integer getArriveat() {
        return arriveat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.arriveAt
     *
     * @param arriveat the value for bnb_order.arriveAt
     *
     * @mbggenerated
     */
    public void setArriveat(Integer arriveat) {
        this.arriveat = arriveat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.cancellationPolicyType
     *
     * @return the value of bnb_order.cancellationPolicyType
     *
     * @mbggenerated
     */
    public Short getCancellationpolicytype() {
        return cancellationpolicytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.cancellationPolicyType
     *
     * @param cancellationpolicytype the value for bnb_order.cancellationPolicyType
     *
     * @mbggenerated
     */
    public void setCancellationpolicytype(Short cancellationpolicytype) {
        this.cancellationpolicytype = cancellationpolicytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.cancellationPolicy
     *
     * @return the value of bnb_order.cancellationPolicy
     *
     * @mbggenerated
     */
    public String getCancellationpolicy() {
        return cancellationpolicy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.cancellationPolicy
     *
     * @param cancellationpolicy the value for bnb_order.cancellationPolicy
     *
     * @mbggenerated
     */
    public void setCancellationpolicy(String cancellationpolicy) {
        this.cancellationpolicy = cancellationpolicy == null ? null : cancellationpolicy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.fullRefundAheadDays
     *
     * @return the value of bnb_order.fullRefundAheadDays
     *
     * @mbggenerated
     */
    public Integer getFullrefundaheaddays() {
        return fullrefundaheaddays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.fullRefundAheadDays
     *
     * @param fullrefundaheaddays the value for bnb_order.fullRefundAheadDays
     *
     * @mbggenerated
     */
    public void setFullrefundaheaddays(Integer fullrefundaheaddays) {
        this.fullrefundaheaddays = fullrefundaheaddays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.guestNumber
     *
     * @return the value of bnb_order.guestNumber
     *
     * @mbggenerated
     */
    public Integer getGuestnumber() {
        return guestnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.guestNumber
     *
     * @param guestnumber the value for bnb_order.guestNumber
     *
     * @mbggenerated
     */
    public void setGuestnumber(Integer guestnumber) {
        this.guestnumber = guestnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_order.tradingRules
     *
     * @return the value of bnb_order.tradingRules
     *
     * @mbggenerated
     */
    public String getTradingrules() {
        return tradingrules;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_order.tradingRules
     *
     * @param tradingrules the value for bnb_order.tradingRules
     *
     * @mbggenerated
     */
    public void setTradingrules(String tradingrules) {
        this.tradingrules = tradingrules == null ? null : tradingrules.trim();
    }
}