package com.payment.entity.groupwormhole;

import com.payment.entity.publicenitty.Entity;

import java.util.Date;

/**
 * Created by shi_y on 2016/9/8.
 */
public class BnbSpaceSourceEntity extends Entity {

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_space_source.spaceId
     *
     * @mbggenerated
     */
    private Long spaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_space_source.vendorId
     *
     * @mbggenerated
     */
    private Integer vendorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_space_source.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_space_source.productId
     *
     * @mbggenerated
     */
    private String productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_space_source.productUrl
     *
     * @mbggenerated
     */
    private String producturl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_space_source.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_space_source.dataChange_LastTime
     *
     * @mbggenerated
     */
    private Date datachangeLasttime;


    private String address;

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_space_source.spaceId
     *
     * @return the value of bnb_space_source.spaceId
     * @mbggenerated
     */
    public Long getSpaceid() {
        return spaceid;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_space_source.spaceId
     *
     * @param spaceid the value for bnb_space_source.spaceId
     * @mbggenerated
     */
    public void setSpaceid(Long spaceid) {
        this.spaceid = spaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_space_source.vendorId
     *
     * @return the value of bnb_space_source.vendorId
     * @mbggenerated
     */
    public Integer getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_space_source.vendorId
     *
     * @param vendorid the value for bnb_space_source.vendorId
     * @mbggenerated
     */
    public void setVendorid(Integer vendorid) {
        this.vendorid = vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_space_source.name
     *
     * @return the value of bnb_space_source.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_space_source.name
     *
     * @param name the value for bnb_space_source.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_space_source.productId
     *
     * @return the value of bnb_space_source.productId
     * @mbggenerated
     */
    public String getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_space_source.productId
     *
     * @param productid the value for bnb_space_source.productId
     * @mbggenerated
     */
    public void setProductid(String productid) {
        this.productid = productid == null ? null : productid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_space_source.productUrl
     *
     * @return the value of bnb_space_source.productUrl
     * @mbggenerated
     */
    public String getProducturl() {
        return producturl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_space_source.productUrl
     *
     * @param producturl the value for bnb_space_source.productUrl
     * @mbggenerated
     */
    public void setProducturl(String producturl) {
        this.producturl = producturl == null ? null : producturl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_space_source.createTime
     *
     * @return the value of bnb_space_source.createTime
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_space_source.createTime
     *
     * @param createtime the value for bnb_space_source.createTime
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_space_source.dataChange_LastTime
     *
     * @return the value of bnb_space_source.dataChange_LastTime
     * @mbggenerated
     */
    public Date getDatachangeLasttime() {
        return datachangeLasttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_space_source.dataChange_LastTime
     *
     * @param datachangeLasttime the value for bnb_space_source.dataChange_LastTime
     * @mbggenerated
     */
    public void setDatachangeLasttime(Date datachangeLasttime) {
        this.datachangeLasttime = datachangeLasttime;
    }
}
