package com.payment.entity.groupwormhole;

import java.util.Date;

public class BnbVirtualUserEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.userType
     *
     * @mbggenerated
     */
    private Short userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.platformId
     *
     * @mbggenerated
     */
    private Short platformId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.platformUID
     *
     * @mbggenerated
     */
    private String platformUID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.nickname
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.avatarUrl
     *
     * @mbggenerated
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.tel
     *
     * @mbggenerated
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.authStatus
     *
     * @mbggenerated
     */
    private Short authStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.idCardType
     *
     * @mbggenerated
     */
    private Short idCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.idCardNo
     *
     * @mbggenerated
     */
    private String idCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.idCardPhotoA
     *
     * @mbggenerated
     */
    private String idCardPhotoA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.idCardPhotoB
     *
     * @mbggenerated
     */
    private String idCardPhotoB;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.statusId
     *
     * @mbggenerated
     */
    private Short statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.avgConfirm
     *
     * @mbggenerated
     */
    private Integer avgConfirm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.responseRate
     *
     * @mbggenerated
     */
    private Float responseRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.isMobileBound
     *
     * @mbggenerated
     */
    private Short isMobileBound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.mobilePhoneBound
     *
     * @mbggenerated
     */
    private String mobilePhoneBound;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bnb_virtualuser.dataChange_LastTime
     *
     * @mbggenerated
     */
    private Date dataChange_LastTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.uid
     *
     * @return the value of bnb_virtualuser.uid
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.uid
     *
     * @param uid the value for bnb_virtualuser.uid
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.userType
     *
     * @return the value of bnb_virtualuser.userType
     * @mbggenerated
     */
    public Short getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.userType
     *
     * @param userType the value for bnb_virtualuser.userType
     * @mbggenerated
     */
    public void setUserType(Short userType) {
        this.userType = userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.platformId
     *
     * @return the value of bnb_virtualuser.platformId
     * @mbggenerated
     */
    public Short getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.platformId
     *
     * @param platformId the value for bnb_virtualuser.platformId
     * @mbggenerated
     */
    public void setPlatformId(Short platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.platformUID
     *
     * @return the value of bnb_virtualuser.platformUID
     * @mbggenerated
     */
    public String getPlatformUID() {
        return platformUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.platformUID
     *
     * @param platformUID the value for bnb_virtualuser.platformUID
     * @mbggenerated
     */
    public void setPlatformUID(String platformUID) {
        this.platformUID = platformUID == null ? null : platformUID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.nickname
     *
     * @return the value of bnb_virtualuser.nickname
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.nickname
     *
     * @param nickname the value for bnb_virtualuser.nickname
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.avatarUrl
     *
     * @return the value of bnb_virtualuser.avatarUrl
     * @mbggenerated
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.avatarUrl
     *
     * @param avatarUrl the value for bnb_virtualuser.avatarUrl
     * @mbggenerated
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.tel
     *
     * @return the value of bnb_virtualuser.tel
     * @mbggenerated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.tel
     *
     * @param tel the value for bnb_virtualuser.tel
     * @mbggenerated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.gender
     *
     * @return the value of bnb_virtualuser.gender
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.gender
     *
     * @param gender the value for bnb_virtualuser.gender
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.description
     *
     * @return the value of bnb_virtualuser.description
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.description
     *
     * @param description the value for bnb_virtualuser.description
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.email
     *
     * @return the value of bnb_virtualuser.email
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.email
     *
     * @param email the value for bnb_virtualuser.email
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.realname
     *
     * @return the value of bnb_virtualuser.realname
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.realname
     *
     * @param realname the value for bnb_virtualuser.realname
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.authStatus
     *
     * @return the value of bnb_virtualuser.authStatus
     * @mbggenerated
     */
    public Short getAuthStatus() {
        return authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.authStatus
     *
     * @param authStatus the value for bnb_virtualuser.authStatus
     * @mbggenerated
     */
    public void setAuthStatus(Short authStatus) {
        this.authStatus = authStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.idCardType
     *
     * @return the value of bnb_virtualuser.idCardType
     * @mbggenerated
     */
    public Short getIdCardType() {
        return idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.idCardType
     *
     * @param idCardType the value for bnb_virtualuser.idCardType
     * @mbggenerated
     */
    public void setIdCardType(Short idCardType) {
        this.idCardType = idCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.idCardNo
     *
     * @return the value of bnb_virtualuser.idCardNo
     * @mbggenerated
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.idCardNo
     *
     * @param idCardNo the value for bnb_virtualuser.idCardNo
     * @mbggenerated
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.idCardPhotoA
     *
     * @return the value of bnb_virtualuser.idCardPhotoA
     * @mbggenerated
     */
    public String getIdCardPhotoA() {
        return idCardPhotoA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.idCardPhotoA
     *
     * @param idCardPhotoA the value for bnb_virtualuser.idCardPhotoA
     * @mbggenerated
     */
    public void setIdCardPhotoA(String idCardPhotoA) {
        this.idCardPhotoA = idCardPhotoA == null ? null : idCardPhotoA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.idCardPhotoB
     *
     * @return the value of bnb_virtualuser.idCardPhotoB
     * @mbggenerated
     */
    public String getIdCardPhotoB() {
        return idCardPhotoB;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.idCardPhotoB
     *
     * @param idCardPhotoB the value for bnb_virtualuser.idCardPhotoB
     * @mbggenerated
     */
    public void setIdCardPhotoB(String idCardPhotoB) {
        this.idCardPhotoB = idCardPhotoB == null ? null : idCardPhotoB.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.statusId
     *
     * @return the value of bnb_virtualuser.statusId
     * @mbggenerated
     */
    public Short getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.statusId
     *
     * @param statusId the value for bnb_virtualuser.statusId
     * @mbggenerated
     */
    public void setStatusId(Short statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.avgConfirm
     *
     * @return the value of bnb_virtualuser.avgConfirm
     * @mbggenerated
     */
    public Integer getAvgConfirm() {
        return avgConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.avgConfirm
     *
     * @param avgConfirm the value for bnb_virtualuser.avgConfirm
     * @mbggenerated
     */
    public void setAvgConfirm(Integer avgConfirm) {
        this.avgConfirm = avgConfirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.responseRate
     *
     * @return the value of bnb_virtualuser.responseRate
     * @mbggenerated
     */
    public Float getResponseRate() {
        return responseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.responseRate
     *
     * @param responseRate the value for bnb_virtualuser.responseRate
     * @mbggenerated
     */
    public void setResponseRate(Float responseRate) {
        this.responseRate = responseRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.isMobileBound
     *
     * @return the value of bnb_virtualuser.isMobileBound
     * @mbggenerated
     */
    public Short getIsMobileBound() {
        return isMobileBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.isMobileBound
     *
     * @param isMobileBound the value for bnb_virtualuser.isMobileBound
     * @mbggenerated
     */
    public void setIsMobileBound(Short isMobileBound) {
        this.isMobileBound = isMobileBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.mobilePhoneBound
     *
     * @return the value of bnb_virtualuser.mobilePhoneBound
     * @mbggenerated
     */
    public String getMobilePhoneBound() {
        return mobilePhoneBound;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.mobilePhoneBound
     *
     * @param mobilePhoneBound the value for bnb_virtualuser.mobilePhoneBound
     * @mbggenerated
     */
    public void setMobilePhoneBound(String mobilePhoneBound) {
        this.mobilePhoneBound = mobilePhoneBound == null ? null : mobilePhoneBound.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.createTime
     *
     * @return the value of bnb_virtualuser.createTime
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.createTime
     *
     * @param createTime the value for bnb_virtualuser.createTime
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bnb_virtualuser.dataChange_LastTime
     *
     * @return the value of bnb_virtualuser.dataChange_LastTime
     * @mbggenerated
     */
    public Date getDataChange_LastTime() {
        return dataChange_LastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bnb_virtualuser.dataChange_LastTime
     *
     * @param dataChange_LastTime the value for bnb_virtualuser.dataChange_LastTime
     * @mbggenerated
     */
    public void setDataChange_LastTime(Date dataChange_LastTime) {
        this.dataChange_LastTime = dataChange_LastTime;
    }
}